### ISSUE TITLE
Problem Running in Cygwin

### ISSUE THREAD

**Issue by konakonah** [coderofsalvation/hubot-script-shellcmd#7] opened 2016-06-29 22:36 UTC
I have installed hubot-script-shellcmd as per instruction
1. npm install hubot-script-shellcmd
2. add 'hubot-script-shellcmd' to external-scripts.json
3. ./bin/hubot

I am getting following error and wondering if I have set up something wrong? Thanks!

```
myhubot> shellcmd
shellcmd
myhubot> shellcmd list
shellcmd list
myhubot> myhubot shellcmd
myhubot shellcmd
myhubot> spawn!
[Thu Jun 30 2016 11:32:52 GMT+1300 (New Zealand Daylight Time)] ERROR Error: spawn C:\myhubot\node_modules\hubot-script-shellcmd\src/../bash/handler ENOENT
  at exports._errnoException (util.js:856:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at nextTickCallbackWith2Args (node.js:474:9)
  at process._tickCallback (node.js:388:17)



myhubot> myhubot shellcmd list
myhubot shellcmd list
myhubot> spawn!
[Thu Jun 30 2016 11:33:01 GMT+1300 (New Zealand Daylight Time)] ERROR Error: spawn C:\myhubot\node_modules\hubot-script-shellcmd\src/../bash/handler ENOENT
  at exports._errnoException (util.js:856:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at nextTickCallbackWith2Args (node.js:474:9)
  at process._tickCallback (node.js:388:17)
```

**Comment by coderofsalvation** [comment] 2016-07-12 04:11
the problem is here:

```
C:\myhubot\node_modules\hubot-script-shellcmd\src/../bash/handler
                                                 ^  ^
                                                 |  |
```

Did you notice that it uses windows slashes () and unix slashes (/) at the same time?
This can be solved by setting the environmnent variable `HUBOT_SHELLCMD`.
For example by running hubot like this:

```
$ HUBOT_SHELLCMD=C:\myhubot\node_modules\hubot-script-shellcmd\src\..\bash/handler  node_modules/.bin/hubot
```

**Comment by coderofsalvation** [comment] 2016-12-20 06:57
did you solve this?

**Comment by coderofsalvation** [comment] 2017-11-10 07:05
closing this.

> Windows users: please do a PR to make this package windowscompatible (i dont use windows unfortunately)

**Closed as completed by coderofsalvation** 2017-11-10 07:05 UTC
