### ISSUE TITLE
Shellcmd run handler 3 times

### ISSUE THREAD

**Issue by vetash** [coderofsalvation/hubot-script-shellcmd#3] opened 2015-07-15 14:42 UTC
So, issue is in header. Do you know how this happens?

**Comment by coderofsalvation** [comment] 2015-07-15 15:01
Hm..do you have some console output to illustrate your issue a bit more?

**Comment by vetash** [comment] 2015-07-15 18:38
Ok, see:
in chat i run simple command `shellcmd helloworld`
in hello world put line:
`sleep 10`
So we can cath in out of ps aux some processes:

```
hubot    19301  0.0  0.2  10760  1192 ?        S    Июл15   0:00 /bin/bash /opt/slack/slack.sh
hubot    19305  0.0 17.6 739956 89580 ?        Sl   Июл15   0:12 node node_modules/hubot/node_modules/.bin/coffee node_modules/.bin/hubot --name HUBOT --adapter slack -l !
hubot    22563  0.1  0.2  10784  1492 ?        S    02:33   0:00 /bin/bash /opt/slack/node_modules/hubot-script-shellcmd/src/../bash/handler helloworld
hubot    22571  0.0  0.1  10784   636 ?        S    02:33   0:00 /bin/bash /opt/slack/node_modules/hubot-script-shellcmd/src/../bash/handler helloworld
hubot    22572  0.0  0.1  10784   644 ?        S    02:33   0:00 /bin/bash /opt/slack/node_modules/hubot-script-shellcmd/src/../bash/handler helloworld
hubot    22573  0.0  0.2  10756  1196 ?        S    02:33   0:00 /bin/bash ./handlers/helloworld
hubot    22574  0.0  0.1   5596   580 ?        S    02:33   0:00 sleep 10
root     22579  0.0  0.1   7856   872 pts/2    S+   02:33   0:00 grep hubot
```

Look at pid `22563` `22571` `22572`

(i'm sorry for my bad english)

**Comment by coderofsalvation** [comment] 2015-07-16 05:30
I can't seem to replicate your issue. I tested it using the most recent hubot + hubot-script-shellcmd:

```
$ .bin/hubot -r hubot-script-shellcmd
Hubot> [Thu Jul 16 2015 07:22:05 GMT+0200 (CEST)] INFO /tmp/node_modules/hubot-script-    shellcmd/index.coffee is using deprecated documentation syntax
[Thu Jul 16 2015 07:22:05 GMT+0200 (CEST)] WARNING Expected /tmp/node_modules/hubot-    script-shellcmd/package to assign a function to module.exports, got object

Hubot> hubot shellcmd
Hubot> available commands:
  helloworld
  update


Hubot> hubot shellcmd helloworld
Hubot> Hello..
Sleepy World!

Hubot> hubot shellcmd helloworld
Hubot> Hello..
Sleepy World!
```

and checked `ps aux` in between the calls:

```
$ ps aux|grep shellcmd
sqz      24344  4.5  1.3 703632 50308 pts/4    Sl+  07:22   0:00 node /usr/bin/coffee .bin/hubot -r     hubot-script-shellcmd
sqz      24488  0.0  0.0  18500  2192 pts/6    S+   07:22   0:00 grep shellcmd
$ ps aux|grep shellcmd
sqz      24344  2.8  1.3 703632 50424 pts/4    Sl+  07:22   0:00 node /usr/bin/coffee .bin/hubot -r     hubot-script-shellcmd
sqz      24531  0.0  0.0  18500  2192 pts/6    S+   07:22   0:00 grep shellcmd
$ ps aux|grep shellcmd
sqz      24344  1.7  1.3 703632 50524 pts/4    Sl+  07:22   0:00 node /usr/bin/coffee .bin/hubot -r     hubot-script-shellcmd
sqz      24589  0.0  0.0  18500  2288 pts/6    S+   07:22   0:00 grep shellcmd
$ 
```

The processes ended fairly quick, hence no duplicate processes are seen.

My theory is that you triggered `shellcmd helloworld` few times _within_ 10 seconds.
Multiple processes show up in `ps aux` since `sleep 10` will have each process wait for at least 10 seconds.
If my theory is correct, changing `sleep 10` into `sleep 10 &` would have different results.

**Comment by vetash** [comment] 2015-07-21 12:54
No, handler is running multiple proceesses instead of 1.
I add sleep 10 for check to handler running script correctly.
`The processes ended fairly quick, hence no duplicate processes are seen.`
Just put sleep 10 to end  of any script and you can see running scripts before they done.

**Comment by coderofsalvation** [comment] 2015-07-21 14:55
Did an update. Could you remove the module, and try `npm install hubot-script-shellcmd` ?

**Comment by vetash** [comment] 2015-07-21 22:34
Yes, now all scripts works fine, but if in script put command like:
`cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 3 | head -n 1`
then handler again run bash script 2 times and stuck on this command.

**Comment by coderofsalvation** [comment] 2016-04-01 09:02
I can't reproduce this..
If you have more debugging info let me know :/

**Comment by coderofsalvation** [comment] 2017-11-10 07:07
im closing this (and will re-open this if other people get this issue too)

**Closed as completed by coderofsalvation** 2017-11-10 07:07 UTC
